### ISSUE TITLE
frame_rate in pitch tracker function can not be set and is aslo mismatching with document

### ISSUE THREAD

**Issue by WelkinYang** [asuni/PitchSqueezer#1] opened 2023-12-28 07:26 UTC
Thank you for your open source F0 extraction algorithm, I found the following problems in the process of using it.
1、The documentation mentions that the parameter to set the number of pitch values per second to output is target_rate, but in the current code it's frame_rate.
2、The frame_rate currently does not work because it uses INTERNAL_RATE, which is set to 100 by default, and cannot be made more accurate by increasing the frame_rate.

**Comment by asuni** [comment] 2024-01-03 14:19
Thanks, updated the documentation. frame_rate should work as intended; while the analysis uses the fixed INTERNAL_RATE, the pitch track is eventually converted to the specified frame_rate.

**Closed as completed** 2024-01-03 14:19 UTC
